### ISSUE TITLE
Integrate nginx and pyramid

### ISSUE THREAD

**Issue by emmorais** [paulo308/bigseaAAA#3]
It is necessary to make nginx and pyramid work together. Nginx may work as a reverse proxy, because it is a good load balancer. Nginx may provide static content too. On the hand hand, Pyramid will be responsible for the REST interface. 

- It is necessary to define if HTTPS will be configured on Nginx or on Pyramid.

**Comment by paulo308** [comment]
On it

**Comment by paulo308** [comment]
Done
